Remove script prepare ~ broken npm install
On the CI this script generates an issue. Which is weird is, we do not
have the issue on ex my computer or a Mac.

proton@e17d1629342d:~/test/webapp$ cat /home/proton/.npm/_logs/2019-11-07T08_32_14_581Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'github:ProtonMail/timezone-support',
1 verbose cli   '--production'
1 verbose cli ]
2 info using npm@6.13.0
3 info using node@v12.13.0
4 verbose npm-session 83f2d76b1ed9cdee
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose prepareGitDep undefined: installing devDeps and running prepare script.
8 error prepareGitDep 1>
8 error prepareGitDep > puppeteer@1.17.0 install /home/proton/.npm/_cacache/tmp/git-clone-46ed3709
/node_modules/puppeteer
8 error prepareGitDep > node install.js
9 error prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=d
ev` instead.
10 silly fetchPackageMetaData error for github:ProtonMail/timezone-support premature close
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 17219ms
13 verbose stack Error: premature close
13 verbose stack     at PassThrough.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-s
tream/index.js:47:67)
13 verbose stack     at PassThrough.emit (events.js:215:7)
13 verbose stack     at emitCloseNT (internal/streams/destroy.js:69:8)
13 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:79:21)
14 verbose cwd /home/proton/test/webapp
15 verbose Linux 5.0.0-32-generic
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "github:ProtonMail/timezone-support
" "--production"
17 verbose node v12.13.0
18 verbose npm  v6.13.0
19 error premature close
20 verbose exit [ 1, true ]

-------------------